/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface AaImg {
    'aa': string;
  }
  interface AaImgAttributes extends StencilHTMLAttributes {
    'aa'?: string;
  }

  interface AaSvg {
    'aa': string;
  }
  interface AaSvgAttributes extends StencilHTMLAttributes {
    'aa'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AaImg': Components.AaImg;
    'AaSvg': Components.AaSvg;
  }

  interface StencilIntrinsicElements {
    'aa-img': Components.AaImgAttributes;
    'aa-svg': Components.AaSvgAttributes;
  }


  interface HTMLAaImgElement extends Components.AaImg, HTMLStencilElement {}
  var HTMLAaImgElement: {
    prototype: HTMLAaImgElement;
    new (): HTMLAaImgElement;
  };

  interface HTMLAaSvgElement extends Components.AaSvg, HTMLStencilElement {}
  var HTMLAaSvgElement: {
    prototype: HTMLAaSvgElement;
    new (): HTMLAaSvgElement;
  };

  interface HTMLElementTagNameMap {
    'aa-img': HTMLAaImgElement
    'aa-svg': HTMLAaSvgElement
  }

  interface ElementTagNameMap {
    'aa-img': HTMLAaImgElement;
    'aa-svg': HTMLAaSvgElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
